# Site settings
title: fabdultf
description: this is a digital space
lang: en-US
timezone: Asia/Riyadh
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Faisal
  #bio: >-
  #  The minimalist Jekyll theme, light and dark mode support, for running a personal site and blog, 
  username: fabdultf
  email: fabdultf@gmail.com
  avatar: /assets/img/avatar.jpg

# Url settings
url: "http://www.fabdultf.com"
baseurl:
permalink: /:title/
#google_analytics:
#fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-postfiles
